
# ...The order of the values is...
#             [x,     y,     z,
#              roll,  pitch, yaw,
#              vx,    vy,    vz,
#              vroll, vpitch,vyaw,
#              ax,    ay,    az]

# world_frame is now the *map* frame
map_frame: um_map
world_frame: um_map

# # Whether to broadcast the transformation over the /tf topic. Defaults to true
# # if unspecified.
publish_tf: false

# # Whether to publish the acceleration state. Defaults to false if unspecified.
publish_acceleration: false

# published by [tum_ardrone] drone_stateestimation
odom0: um/tum_ekf  # tum_ardrone EKF output, including fused PTAM

# values are extracted from tum_ardrone/msg/filter_state.msg
odom0_config: [true,  true,  true,  # absolute position
               false, false, false,
               false, false, false, # ignore velocity in favor of position
               false, false, false,
               false, false, false] # doesn't report accelerations
odom0_differential: false
odom0_relative: true
odom0_queue_size: 30
# odom0_rejection_threshold: 2
odom0_nodelay: false
